fix bug in generate.py and add necessary deps for apple silicon
1. I got the following error having to do with a .replace() call, and fixed with an update to chart_writer.py:

```
python generate.py ./test.mp3
Loading model: 3podi/charter-v1.0-40-M-best-acc
Using a slow image processor as `use_fast` is unset and a slow processor was saved with this model. `use_fast=True` will be the default behavior in v4.52, even if the model was saved with a slow processor. This will result in minor differences in outputs. You'll still be able to use a slow processor with `use_fast=False`.
Generating chart for: ./test.mp3
Let's rock!: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 750/750 [02:15<00:00,  5.53it/s]
Traceback (most recent call last):
  File "/Users/melvillian/code/audio2chart/generate.py", line 106, in <module>
    main()
    ~~~~^^
  File "/Users/melvillian/code/audio2chart/generate.py", line 88, in main
    filled_text = fill_expert_single(decoded_full, metadata=metadata)
  File "/Users/melvillian/code/audio2chart/chart/chart_writer.py", line 41, in fill_expert_single
    template_text = template_text.replace(f'###{str(key)}###', value)
TypeError: replace() argument 2 must be str, not int
```

2. there were various pip deps I needed to install to get the example working:

pip install torch torchvision torchaudio librosa